### ISSUE TITLE
Pages - Waits

### ISSUE THREAD

**Issue by katiholasz** [pitpalac36/trello-api#1]
For BoardPage.cs, HomePage.cs and LoginPage.cs
```
 WaitHelpers.WaitUntilElementIsVisible(_addListPane);  
 WaitHelpers.WaitUntilElementIsVisible(_listNameInput);
 WaitHelpers.WaitUntilElementIsVisible(_boardNamePane);
```

- [ ]  if you are using the helpers from NS Framework, let's use their version of  **WaitUntilElementIsVisible**

**Comment by katiholasz** [comment]
public volatile static IList<Board> _currentBoards = new List<Board>();

Order of modifiers declaration, you can read here more about this: 
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/trello-api/commit/52b57c40f933348710aef776117236653d874b15

It works! :D
