### ISSUE TITLE
Order of modifiers declaration

### ISSUE THREAD

**Issue by katiholasz** [pitpalac36/trello-api#2]
public volatile static IList _currentBoards = new List();

- [ ] Order of modifiers declaration, you can read here more about this: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/trello-api/commit/f66e8f8f1f99177b7c9eece25de6f362d9255ca2
